import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ThemeProviderWrapper from '@/app/components/ThemeProviderWrapper';
import '@/app/[locale]/globals.css';
import { getMessages } from 'next-intl/server';
import { Locale } from '@/i18n/routing';
import { NextIntlClientProvider } from 'next-intl';
import Header from '@/app/components/Header';
import AuthProvider from '@/app/[locale]/AuthProvider';
import 'react-photo-view/dist/react-photo-view.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: { locale: Locale };
}>) {
    const { locale } = await params;
    const messages = await getMessages();
    return (
        <html lang={locale}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <ThemeProviderWrapper>
                    <AuthProvider>
                        <NextIntlClientProvider messages={messages}>
                            <div id="root">
                                <Header />
                                {children}
                            </div>
                        </NextIntlClientProvider>
                    </AuthProvider>
                </ThemeProviderWrapper>
            </body>
        </html>
    );
}
